/*
These queries can be executed to load our tables with sample data, so we can test the data model and SQL logic
*/
---RANDOM DATA INSERT
DELETE FROM PV_PC.USERS_LOCATION;
INSERT INTO PV_PC.USERS_LOCATION  -- INSERT DATA FOR THE PREVIOUS 10 DAYS
(
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-1) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-2) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-3) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-4) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-5) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-6) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-7) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-8) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-9) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS ROW_ID ,DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-10) AS EVENT_DATETIME, cast (random() * 300 as int) AS USER_ID,  PV_PC.RANDOMTEXT() AS POST_CODE, GETDATE() AS LOAD_DATE FROM FINANCE.USERS_EXTRACT
);

-- DELETE DUPLICATE IF AVAILABLE, THIS TABLE SHOULD ONLY HOLD 1 ROW PER USER PER HOUR
DELETE FROM PV_PC.USERS_LOCATION WHERE ROW_ID IN
  (SELECT ROW_ID FROM
  (SELECT A.*, ROW_NUMBER() OVER (PARTITION BY A.USER_ID,DATE_TRUNC('hour',EVENT_DATETIME) ORDER BY A.LOAD_DATE ASC) RNK FROM PV_PC.USERS_LOCATION  A ) WHERE RNK != 1);
-- DELETE DUPLICATE IF AVAILABLE


DELETE FROM PV_PC.PAGEVIEWS;
INSERT INTO PV_PC.PAGEVIEWS
  (
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT() +'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-1) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * - 5 AS INT), GETDATE()-2) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-3) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-4) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-5) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-6) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-7) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-8) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-9) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
  UNION
  SELECT PV_PC.UUID() AS EVENT_ID, cast (random() * 300 as int) AS USER_ID, DATEADD(HOUR, CAST(random() * -5 AS INT), GETDATE()-10) AS PAGEVIEW_DATETIME,'www.'+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+PV_PC.RANDOMTEXT()+'.com' AS PAGE_URL, GETDATE() AS LOAD_DATE FROM FINANCE.PAGEVIEWS_EXTRACT
);

-- DELETE DUPLICATE IF AVAILABLE
DELETE FROM PV_PC.PAGEVIEWS WHERE EVENT_ID IN
  (SELECT EVENT_ID FROM
  (SELECT EVENT_ID, ROW_NUMBER() OVER (PARTITION BY USER_ID, PAGEVIEW_DATETIME,PAGE_URL ORDER BY A.LOAD_DATE ASC) RNK FROM PV_PC.PAGEVIEWS  A ) WHERE RNK != 1);
-- DELETE DUPLICATE IF AVAILABLE
