"""
The queries below is used to update PV_PC.PAGEVIEWS from the source table PAGEVIEWS_EXTRACT at an hourly interval: execution time 5mins past the hour
"""
--- EXECUTE THIS DAILY AT 5 MINS PAST THE HOUR -- DEPENDING ON HOW LONG IT TAKES FOR THE SOURCE TABLE TO LOAD
DELETE FROM PV_PC.PAGEVIEWS WHERE EVENT_DATETIME::DATE >= CURRENT_DATE-1 AND EVENT_DATETIME::DATE <= CURRENT_DATE-1; -- DELETE PREVIOUS DAYS DATA, THERE SHOULDN'T BE ANY DATA TO DELETE BUT JUST IN CASE THERE WAS A MANUAL LOAD
  INSERT INTO PV_PC.PAGEVIEWS
  SELECT fn_uuid() AS EVENT_ID, USER_ID, PAGEVIEW_DATETIME, PAGE_URL, GETDATE() AS LOAD_DATE FROM PAGEVIEWS_EXTRACT;
--- EXECUTE THIS DAILY AT 5 MINS PAST THE HOUR -- DEPENDING ON HOW LONG IT TAKES FOR THE SOURCE TABLE TO LOAD

-- DELETE DUPLICATE IF AVAILABLE
DELETE FROM PV_PC.PAGEVIEWS WHERE EVENT_ID IN
  (SELECT EVENT_ID FROM
  (SELECT EVENT_ID, ROW_NUMBER() OVER (PARTITION BY USER_ID, PAGEVIEW_DATETIME,PAGE_URL ORDER BY A.LOAD_DATE ASC) RNK FROM PV_PC.PAGEVIEWS  A ) WHERE RNK != 1);
-- DELETE DUPLICATE IF AVAILABLE
