/*
This script aggregates the data in the user_location and pageviews table to help answer the questions below

Depending on how many rows returned we could also create a materialized view instead of table therefore eliminating an extract etl step
*/

--- INSERT DATA INTO FINAL TABLE
DELETE FROM PV_PC.PV_PER_POSTCODE  -- WE NEED EXECUTE A FULL REFRESH SO WE ALL RETRIEVE THE LATEST POSTCODE FOR EACH USER
  INSERT INTO PV_PC.PV_PER_POSTCODE
  WITH UL AS
            (SELECT USER_ID, DATE_TRUNC('hour',EVENT_DATETIME) EVENT_DATETIME, POST_CODE,
               ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY DATE_TRUNC('hour',EVENT_DATETIME) DESC ) RNK FROM PV_PC.USERS_LOCATION)
  , PE AS (SELECT DATE_TRUNC('hour',PAGEVIEW_DATETIME) PV_DATETIME, USER_ID , COUNT(EVENT_ID) PVS FROM PV_PC.PAGEVIEWS GROUP BY 1,2)
  SELECT
   PE.PV_DATETIME
  ,UL.POST_CODE
  ,SUM(CASE WHEN UL.RNK = 1 THEN PE.PVS ELSE 0 END ) LAST_POSTCODE_PVS
  ,SUM(PE.PVS) PVS
  ,GETDATE() AS LOAD_DATE
  FROM UL JOIN PE ON UL.USER_ID = PE.USER_ID AND PE.PV_DATETIME  =  UL.EVENT_DATETIME
  GROUP BY 1,2;
  ---- INSERT DATA INTO FINAL TABLE
